### PR TITLE
Remove unused build to lib

### PR DESCRIPTION
**Pull request by renkun-ken**
https://github.com/ManuelHentschel/VSCode-R-Debugger/pull/7#issuecomment-634619993

### CODE REVIEW

**Comment by ManuelHentschel** [comment]
I have switched to installing the development version of the package globally and using a `./lib/` directory only in projects where i explicitly want to use the 'stable' version. My local `build.R` looks like this:
``` r
devtools::document()
devtools::install(args = c('--no-lock'), reload = FALSE, build = FALSE)
```
Would this work for you too?

I'm using `build=FALSE` to make sure the `srcref`s of the package functions point to the proper files and not a temporary copy of the files used when installing from an intermediate `...tar.gz`.

**Comment by renkun-ken** [comment]
Your local `build.R` works perfectly for me. I only need development version everywhere. Then it seems there's no need to keep `VSCode-R-Debugger/tet/R/lib` and `.Rprofile`.

**Comment by renkun-ken** [comment]
Would you mind I change this PR to your version of `build.R` and file a PR at VSCode-R-Debugger about removing the `lib` and `.Rprofile` if no longer needed?

**Comment by ManuelHentschel** [comment]
Sounds good :)

**Pull request merged**
