### PR TITLE
Custom attributes

### PR DESCRIPTION
**Pull request by ManuelHentschel**
Implements internal Attributes suggested in https://github.com/ManuelHentschel/vscDebugger/issues/50#issuecomment-640947413

### CODE REVIEW

**Comment by renkun-ken** [comment]
I'm a bit confused whether the custom attributes is designed for vscDebugger developer or end-user? From https://github.com/ManuelHentschel/VSCode-R-Debugger/pull/43/files, it seems user could define their own attributes to present in object information.

One problem is that if user put it in `~/.Rprofile`, then user has to `library(vscDebugger)` before calling `.vsc.addVarInfo`, which is not necessary for non-debugging session. I guess the following could work:

Put the following in `.Rprofile` and the user customizations should work.

```r
if (Sys.getenv("VSCODE_DEBUG_SESSION") == 1) {
  vscDebugger::.vsc.addVarInfo(...)
}
```

**Comment by ManuelHentschel** [comment]
My thoughts were the following, but the entire structure is of course up for discussion:

The entry `customAttributes` is meant for non-essential entries that give additional information about a variable. Currently, these are e.g. `__body()`, `__unclass()`, `__bytes`. Since these are independent from each other, this entry stacks (all `customAttributes` are read, not just the first one). Their names should be `__xxx` to identify them as info added by the debugger, which is not actually part of the variable.

The entry `internalAttributes` is meant to give flexibility when showing custom variables like promises and ellipses. Here the attributes are used to show essential informtion about an individual variable type, hence this entry does not stack and one has to be careful not to overwrite the `internalAttributes` defined in other `varInfo`s.

In general, both of these can be used by users and developers, but the `internalAttributes` are probably only sensible when implementing a custom `varInfo` (--> rather done by developers) whereas `customAttributes` can be used to simply show additional information like bytes, maximum of a list, etc. (--> also done by end-users).

**Comment by ManuelHentschel** [comment]
The entire idea of defining custom `varInfo`s etc. is not really meant to be included in normal code, but rather in the `.Rprofile` etc., so the if clause you suggested would be a sensible approach to implement this.

**Comment by tdeenes** [comment]
I like the idea of `customAttributes` and `internalAttributes`, and also support the conditional entry in the .Rprofile file.

**Pull request merged**
